### PR TITLE
Rebuild for Python 3.12

### PR DESCRIPTION
**Pull request by jfrost-mo**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Previously the automatic python 3.12 migration failed because the release version of 3.12 wasn't out, so this PR should prompt it to retry now it is. It also fixes the licence being out of date after the upstream repository was relicenced to BSD.

### CODE REVIEW

**Comment by jfrost-mo** [comment]
@conda-forge-admin, please rerender

**Comment by jfrost-mo** [comment]
Hmm. It seems that the builds are still failing to compile the cython bits. I'm not convinced this is Python 3.12 related as the other versions are also failing.

```
Error compiling Cython file:
------------------------------------------------------------
...
                    unsigned char* packed_data,
                    int* packed_length,
                    function* parent) nogil


cdef void MO_syslog(int value, char* message, const function* const caller):
     ^
------------------------------------------------------------

lib/mo_pack/_packing.pyx:67:5: Function signature does not match previous declaration
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/mo_pack_1696586859766/work/setup.py", line 34, in <module>
    ext_modules=cythonize(extensions),
                ^^^^^^^^^^^^^^^^^^^^^
  File "/home/conda/feedstock_root/build_artifacts/mo_pack_1696586859766/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
Compiling lib/mo_pack/_packing.pyx because it changed.
[1/1] Cythonizing lib/mo_pack/_packing.pyx
    cythonize_one(*args)
  File "/home/conda/feedstock_root/build_artifacts/mo_pack_1696586859766/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python3.12/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: lib/mo_pack/_packing.pyx
Traceback (most recent call last):
  File "/opt/conda/bin/conda-mambabuild", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 256, in main
    call_conda_build(action, config)
  File "/opt/conda/lib/python3.10/site-packages/boa/cli/mambabuild.py", line 228, in call_conda_build
    result = api.build(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/api.py", line 180, in build
    return build_tree(
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 3078, in build_tree
    packages_from_this = build(metadata, stats,
  File "/opt/conda/lib/python3.10/site-packages/conda_build/build.py", line 2198, in build
    utils.check_call_env(cmd, env=env, rewrite_stdout_env=rewrite_env,
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 451, in check_call_env
    return _func_defaulting_env_to_os_environ("call", *popenargs, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/conda_build/utils.py", line 427, in _func_defaulting_env_to_os_environ
    raise subprocess.CalledProcessError(proc.returncode, _args)
subprocess.CalledProcessError: Command '['/bin/bash', '-o', 'errexit', '/home/conda/feedstock_root/build_artifacts/mo_pack_1696586859766/work/conda_build.sh']' returned non-zero exit status 1.
##[error]Bash exited with code '1'.
```

The pertinent line is:
```
lib/mo_pack/_packing.pyx:67:5: Function signature does not match previous declaration
```

**Comment by jfrost-mo** [comment]
I'll be honest, I don't really know enough (any) cython to be able to debug this.

**Comment by trexfeathers** [comment]
> I'll be honest, I don't really know enough (any) cython to be able to debug this.

@jfrost-mo I'm afraid that's also the situation within the maintenance team, too.

**Comment by jfrost-mo** [comment]
I'm currently doing a course on C, so I'll try and come back to this in a couple weeks and see if i have gained the knowledged to get it working.

**Comment by bjlittle** [comment]
@jfrost-mo I'll take a look, no bother :+1:

**Comment by ocefpaf** [comment]
The bot will re-issue #31 soon. Let's wait for it. Closing this one.

**Pull request closed without merging**
