### PR TITLE
rerender

### PR DESCRIPTION
**Pull request by ocefpaf**
This feedstock we living in the stone age. Bring it back to the modern era.

### CODE REVIEW

**Comment by ocefpaf** [comment]
Travis-CI is not starting. Probably because this is an old feedstocks created before staged-recipes.

**Comment by pelson** [comment]
> Travis-CI is not starting. Probably because this is an old feedstocks created before staged-recipes.

Seems to have started now.

```
Error:  Package missing in current osx-64 channels: 
  - libmo_unpack
```

**Comment by ocefpaf** [comment]
> Seems to have started now.

I activated is manually.

**Comment by ocefpaf** [comment]
Closing in favor of #1

**Pull request closed without merging**
