### PR TITLE
Release v0.3.0

### PR DESCRIPTION
**Pull request by bjlittle**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] ~Bumped the build number (if the version is unchanged)~
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by bjlittle** [comment]
@conda-forge-admin, please rerender

**Comment by bjlittle** [comment]
@ocefpaf Happy days 🥳

**Comment by bjlittle** [comment]
Cheers @ocefpaf - I've lost count of the number of beers that I owe you btw 🤣

**Comment by bjlittle** [comment]
@ocefpaf Is there something in particular that needs to be done on the feedstock to enable python_abi 3.12 support? 

Or will that happen in the fullness of time?

**Comment by ocefpaf** [comment]
The bot will do it. I'll check if there are any problems with it...

**Pull request merged**
